import type { Metadata } from "next";
import "./globals.css";
import Appsidebar from "@/pages/app-sidebar/Appsidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="flex">
          {/* Sidebar */}
          <div className="w-3/12 flex-none bg-gray-800 h-screen">
            <Appsidebar />
          </div>

          {/* Main Content */}
          <main className="flex-9/12 px-2 py-4 bg-white">{children}</main>
        </div>
      </body>
    </html>
  );
}
